apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-service-deployment
  labels:
    app: config-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-service
  template:
    metadata:
      labels:
        app: config-server-service
    spec:
      containers:
      - name: config-server-service
        image: sravanpalakala/config-server-service
        ports:
        - containerPort: 8888