spring:
  cloud:
    config:
      uri: http://CONFIG-SERVER
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  file:
    name: /Users/ravi/Desktop/logs/user-service/user-service.log

url:
  holiday: http://3.236.229.114:32651/holidays
  leave: http://3.236.229.114:32512/leave

kafka:
  boot:
    server: localhost:9092
  topic:
    name: lamina-topic
  consumer:
    group:
      id: lamina-group-id
