apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: api-gateway-service
spec:
 replicas: 1
 template:
  metadata:
   labels:
    name: api-gateway-service
  spec:
    containers:
   - name: api-gateway-service
     image: sravanpalakala/api-gateway-service
     ports:
     - containerPort: 8085
     - containerPort: 50000
    

