apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: sravanpalakala/api-gateway-service
        ports:
        - containerPort: 8085