spring:
  cloud:
    config:
      uri: http://CONFIG-SERVER
    server:
      git:
        uri: https://github.com/ravichandrap/laminatimes
  application:
    name: user-service
  h2:
    console:
      settings:
        trace: true
        web-allow-others: false

server:
  port: 8123

logging:
  file:
    name: user-service.log

url:
  holiday: http://localhost:8088/holidays
  leave: http://localhost:8086/leave

debug: false


