spring:
  cloud:
    config:
      uri: http://CONFIG-SERVER
  application:
    name: user-service
server:
  port: 8123

logging:
  file:
    name: user-service.log

url:
  holiday: http://3.236.229.114:31082/holidays
  leave: http://3.236.229.114:31082/leave

kafka:
  boot:
    server: localhost:9092
  topic:
    name: myTopic-kafkasender
