logging:
  file:
    name: ../stock-market-service.log
  level:
    com: DEBUG

server:
  port: 8092

spring:
  datasource:
    data: data.sql
    initialization-mode: always
  application:
    name: stock-market-service
  cloud:
    config:
      uri: http://CONFIG-SERVER
      server:
        git:
          uri: https://github.com/ravichandrap/laminatimes
  profiles:
    active: prod

url:
  holiday: http://localhost:31082/holidays
  leave: http://localhost:31082/leave

debug: false


